# Description: This file contains the lineups dictionary that is used to generate the lineups

# ROLE LEGEND (based on StatsBomb terminology):

# Goalkeeper [GK]
# Center Back [CB]
# Left Center Back [LCB]
# Right Center Back [RCB]
# Left Back [LB]
# Right Back [RB]
# Left Wing Back [LWB]
# Right Wing Back [RWB]
# Center Defensive Midfield [CDM]
# Left Defensive Midfield [LDM]
# Right Defensive Midfield [RDM]
# Center Midfield [CM]
# Left Center Midfield [LCM]
# Right Center Midfield [RCM]
# Center Attacking Midfield [CAM]
# Left Attacking Midfield [LAM]
# Right Attacking Midfield [RAM]
# Left Midfield [LM]
# Right Midfield [RM]
# Left Wing [LW]
# Right Wing [RW]
# Center Forward [CF]
# Left Center Forward [LCF]
# Right Center Forward [RCF]
# Secondary Striker [SS]


formations = {
    "3142": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "32221": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "3232": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "3412": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "3421": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Left Attacking Midfield", "abbr": "LAM", "x": 50, "y": 30},
        {"role": "Right Attacking Midfield", "abbr": "RAM", "x": 50, "y": 50},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "343": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "3511": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "352": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "41212": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "41221": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "4141": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "42121": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "42211": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "4222": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "4231": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Left Attacking Midfield", "abbr": "LAM", "x": 50, "y": 30},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Right Attacking Midfield", "abbr": "RAM", "x": 50, "y": 50},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "4312": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Defensive Midfield", "abbr": "LDM", "x": 32, "y": 30},
        {"role": "Right Defensive Midfield", "abbr": "RDM", "x": 32, "y": 50},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "4321": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Center Defensive Midfield", "abbr": "CDM", "x": 32, "y": 40},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Attacking Midfield", "abbr": "LAM", "x": 50, "y": 30},
        {"role": "Right Attacking Midfield", "abbr": "RAM", "x": 50, "y": 50},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "433": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "4411": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Center Attacking Midfield", "abbr": "CAM", "x": 50, "y": 40},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "442": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "451": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Midfield", "abbr": "LM", "x": 40, "y": 15},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Right Midfield", "abbr": "RM", "x": 40, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
    ],
    "5221": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Back", "abbr": "LB", "x": 20, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Back", "abbr": "RB", "x": 20, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Wing", "abbr": "LW", "x": 50, "y": 15},
        {"role": "Right Wing", "abbr": "RW", "x": 50, "y": 65},
        {"role": "Center Forward", "abbr": "CF", "x": 60, "y": 40},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
    ],
    "532": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Center Forward", "abbr": "LCF", "x": 60, "y": 35},
        {"role": "Right Center Forward", "abbr": "RCF", "x": 60, "y": 45},
    ],
    "541": [
        {"role": "Goalkeeper", "abbr": "GK", "x": 5, "y": 40},
        {"role": "Left Wing Back", "abbr": "LWB", "x": 30, "y": 15},
        {"role": "Left Center Back", "abbr": "LCB", "x": 20, "y": 30},
        {"role": "Center Back", "abbr": "CB", "x": 20, "y": 40},
        {"role": "Right Center Back", "abbr": "RCB", "x": 20, "y": 50},
        {"role": "Right Wing Back", "abbr": "RWB", "x": 30, "y": 65},
        {"role": "Left Center Midfield", "abbr": "LCM", "x": 40, "y": 30},
        {"role": "Center Midfield", "abbr": "CM", "x": 40, "y": 40},
        {"role": "Right Center Midfield", "abbr": "RCM", "x": 40, "y": 50},
        {"role": "Left Attacking Midfield", "abbr": "LAM", "x": 50, "y": 30},
        {"role": "Right Attacking Midfield", "abbr": "RAM", "x": 50, "y": 50},
    ],
}


